(function () {
  'use strict';

  const PLUGIN_ID = 'stage-theater';
  const ROOT_ID = 'stg-root';
  const STYLE_ID = 'stg-critical-style';
  const SETTINGS_KEY = 'stage-theater-settings-v2';
  const VERSION = '2.0.0';
  const icon = '<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 8c2-2 5-2 8 0 3-2 6-2 8 0v4c0 4-3 7-8 8-5-1-8-4-8-8V8z"/><path d="M8 12h.01M16 12h.01M9 16c2 1 4 1 6 0"/></svg>';
  function iconFor(name) {
    const paths = { close: '<path d="M6 6l12 12M18 6L6 18"/>', collapse: '<path d="M5 9l7 7 7-7"/>', refresh: '<path d="M20 11a8 8 0 0 0-14.7-4L3 10m0 0V4m0 6h6M4 13a8 8 0 0 0 14.7 4L21 14m0 0v6m0-6h-6"/>', star: '<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9L12 3z"/>', copy: '<rect x="8" y="8" width="11" height="11" rx="1"/><path d="M16 8V5H5a1 1 0 0 0-1 1v11h4"/>', edit: '<path d="m4 16-.7 4 4-.7L19 7.6a2.1 2.1 0 0 0-3-3L4 16zM14.5 6.5l3 3"/>', trash: '<path d="M4 7h16M10 11v6M14 11v6M6 7l1 14h10l1-14M9 7V4h6v3"/>', up: '<path d="m6 14 6-6 6 6"/>', down: '<path d="m6 10 6 6 6-6"/>' };
    return '<svg viewBox="0 0 24 24" aria-hidden="true">' + (paths[name] || '') + '</svg>';
  }

  function makeId() { return 'stg_' + Date.now().toString(36) + '_' + Math.random().toString(36).slice(2, 8); }
  function escapeHtml(value) { return String(value == null ? '' : value).replace(/[&<>"']/g, function (c) { return ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]; }); }
  function clone(value) { try { return JSON.parse(JSON.stringify(value)); } catch (_) { return value; } }
  function context() { try { return window.SillyTavern && typeof window.SillyTavern.getContext === 'function' ? (window.SillyTavern.getContext() || {}) : {}; } catch (_) { return {}; } }
  function messages() { const c = context(); return Array.isArray(c.chat) ? c.chat : []; }
  function bodyOf(message) { return String(message && (message.mes != null ? message.mes : message.content != null ? message.content : '') || ''); }
  function isUser(message) { return !!(message && (message.is_user || message.role === 'user')); }
  function isSystem(message) { return !!(message && (message.is_system || message.role === 'system')); }
  function isAssistant(message) { return !!message && !isUser(message) && !isSystem(message); }
  function messageKey(index, message) { return String(message && (message.id != null ? message.id : message.send_date != null ? message.send_date : message.gen_id != null ? message.gen_id : index)); }
  function hash(value) { let result = 0; const source = String(value || ''); for (let i = 0; i < source.length; i++) result = ((result << 5) - result + source.charCodeAt(i)) | 0; return String(result >>> 0); }

  const defaults = { enabled: true, autoGenerate: false, chatDefaultEnabled: true, contextDepth: 10, sendWorldbook: false, sendCharacterCard: true, sendPreviousUser: true, promptMode: 'merged', allowScripts: false, activeProfile: 'default', fab: { right: 18, bottom: 86 }, profiles: [{ id: 'default', name: '默认 API', baseUrl: '', apiKey: '', model: '', temperature: 0.9, maxTokens: 800, stream: false }], prompts: [{ id: makeId(), name: '默认小剧场', category: '通用', note: '', enabled: true, text: '请根据角色卡设定、当前对话和触发的 AI 回复，生成一个贴合气氛的小剧场。可以使用基础 HTML 排版，只输出小剧场正文。' }] };
  let settings = loadSettings();
  let initialized = false;
  let subscribed = false;
  let generating = false;
  let pendingSignature = '';
  let pendingSince = 0;
  let generatedSignature = '';
  let drag = null;
  let skipClickUntil = 0;

  function loadSettings() {
    let stored = null;
    try { stored = JSON.parse(window.localStorage.getItem(SETTINGS_KEY) || 'null'); } catch (_) {}
    if (!stored) { try { const store = context().extensionSettings || window.extension_settings; stored = store && store[PLUGIN_ID]; } catch (_) {} }
    const result = Object.assign(clone(defaults), stored || {});
    result.fab = Object.assign({}, defaults.fab, stored && stored.fab || {});
    result.profiles = Array.isArray(stored && stored.profiles) && stored.profiles.length ? stored.profiles : clone(defaults.profiles);
    result.prompts = Array.isArray(stored && stored.prompts) && stored.prompts.length ? stored.prompts : clone(defaults.prompts);
    return result;
  }
  function saveSettings() {
    try { window.localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings)); } catch (_) {}
    try { const c = context(), store = c.extensionSettings || window.extension_settings; if (store) store[PLUGIN_ID] = clone(settings); if (typeof c.saveSettingsDebounced === 'function') c.saveSettingsDebounced(); else if (typeof window.saveSettingsDebounced === 'function') window.saveSettingsDebounced(); } catch (_) {}
  }
  function chatData() { const c = context(); c.chatMetadata = c.chatMetadata || {}; c.chatMetadata.extensions = c.chatMetadata.extensions || {}; c.chatMetadata.extensions[PLUGIN_ID] = c.chatMetadata.extensions[PLUGIN_ID] || { enabled: settings.chatDefaultEnabled, theaters: {} }; const data = c.chatMetadata.extensions[PLUGIN_ID]; data.theaters = data.theaters || {}; if (typeof data.enabled !== 'boolean') data.enabled = settings.chatDefaultEnabled; return data; }
  function saveChat() { const c = context(); try { if (typeof c.saveChat === 'function') c.saveChat(); } catch (_) {} try { if (typeof window.saveChatConditional === 'function') window.saveChatConditional(); } catch (_) {} try { if (typeof window.saveChat === 'function') window.saveChat(); } catch (_) {} }

  function injectCriticalStyle() { if (document.getElementById(STYLE_ID)) return; const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = '#stg-root{position:fixed!important;inset:0!important;width:100vw!important;height:100vh!important;z-index:2147483000!important;pointer-events:none!important}#stg-root .stg-fab,#stg-root .stg-panel{pointer-events:auto!important}#stg-root .stg-fab{position:fixed!important;right:18px;bottom:86px;width:58px;height:58px;border:2px solid #fff;border-radius:50%;background:#126e82;color:#fff;box-shadow:0 12px 30px rgba(0,0,0,.45);display:grid!important;place-items:center;z-index:2147483646!important;cursor:pointer;touch-action:none;opacity:1!important;visibility:visible!important}#stg-root .stg-fab svg{width:26px;height:26px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}#stg-root .stg-panel{position:fixed;right:18px;bottom:154px;width:min(450px,calc(100vw - 20px));max-height:calc(100vh - 24px);background:#f8fafc;color:#17212b;border:1px solid #94a3b8;border-radius:8px;box-shadow:0 18px 60px rgba(0,0,0,.38);overflow:hidden;z-index:2147483645;display:none}#stg-root .stg-panel.stg-open{display:flex;flex-direction:column}'; (document.head || document.documentElement).appendChild(style); }
  function mount() { if (!document.body) return false; if (document.getElementById(ROOT_ID)) return true; injectCriticalStyle(); const root = document.createElement('div'); root.id = ROOT_ID; root.setAttribute('data-stage-theater', VERSION); root.style.cssText = 'position:fixed;inset:0;width:100vw;height:100vh;z-index:2147483000;pointer-events:none;'; root.innerHTML = '<button class="stg-fab" data-stg-action="toggle" type="button" title="小剧场设置">' + icon + '</button><section class="stg-panel" data-stg-panel><header class="stg-panel-head"><strong>小剧场生成器</strong><button class="stg-icon-btn" data-stg-action="close" type="button" title="关闭">' + iconFor('close') + '</button></header><nav class="stg-tabs"><button class="stg-tab stg-active" data-stg-tab="general" type="button">总控</button><button class="stg-tab" data-stg-tab="api" type="button">API</button><button class="stg-tab" data-stg-tab="prompts" type="button">提示词</button><button class="stg-tab" data-stg-tab="history" type="button">历史</button><button class="stg-tab" data-stg-tab="manual" type="button">手动</button></nav><main class="stg-body"><section data-stg-section="general" class="stg-section stg-active"></section><section data-stg-section="api" class="stg-section"></section><section data-stg-section="prompts" class="stg-section"></section><section data-stg-section="history" class="stg-section"></section><section data-stg-section="manual" class="stg-section"></section><div class="stg-status" data-stg-status></div></main></section>'; document.body.appendChild(root); placeFab(); bindFab(); renderAll(); return true; }
  function bindFab() { const fab = document.querySelector('#' + ROOT_ID + ' .stg-fab'); if (!fab || fab.dataset.stgBound) return; fab.dataset.stgBound = '1'; fab.addEventListener('pointerdown', pointerDown, { passive: true }); fab.addEventListener('pointermove', pointerMove, { passive: true }); fab.addEventListener('pointerup', pointerUp, { passive: true }); fab.addEventListener('pointercancel', pointerUp, { passive: true }); }
  function pointerDown(event) { drag = { pointerId: event.pointerId, x: event.clientX, y: event.clientY, right: Number(settings.fab.right), bottom: Number(settings.fab.bottom), moved: false }; try { event.currentTarget.setPointerCapture(event.pointerId); } catch (_) {} }
  function pointerMove(event) { if (!drag || drag.pointerId !== event.pointerId) return; const dx = event.clientX - drag.x, dy = event.clientY - drag.y; if (Math.abs(dx) + Math.abs(dy) > 6) drag.moved = true; const fab = event.currentTarget; settings.fab.right = Math.max(8, Math.min(Math.max(8, innerWidth - fab.offsetWidth - 8), drag.right - dx)); settings.fab.bottom = Math.max(8, Math.min(Math.max(8, innerHeight - fab.offsetHeight - 8), drag.bottom - dy)); placeFab(); }
  function pointerUp(event) { if (!drag || drag.pointerId !== event.pointerId) return; const clicked = !drag.moved; drag = null; saveSettings(); if (clicked) { skipClickUntil = Date.now() + 400; togglePanel(); } }
  function placeFab() { const fab = document.querySelector('#' + ROOT_ID + ' .stg-fab'), panel = document.querySelector('#' + ROOT_ID + ' [data-stg-panel]'); if (fab) { fab.style.right = Math.max(8, Number(settings.fab.right) || 18) + 'px'; fab.style.bottom = Math.max(8, Number(settings.fab.bottom) || 86) + 'px'; } if (panel) { panel.style.right = Math.max(10, Number(settings.fab.right) || 18) + 'px'; panel.style.bottom = Math.max(70, (Number(settings.fab.bottom) || 86) + 66) + 'px'; } }
  function bindEvents() { if (document.documentElement.dataset.stgEventsBound) return; document.documentElement.dataset.stgEventsBound = '1'; document.addEventListener('click', onClick, true); document.addEventListener('change', onChange, true); document.addEventListener('input', onInput, true); }
  function onClick(event) { const tab = event.target && event.target.closest ? event.target.closest('[data-stg-tab]') : null, actionEl = event.target && event.target.closest ? event.target.closest('[data-stg-action]') : null, theater = event.target && event.target.closest ? event.target.closest('[data-stg-theater-action]') : null, root = document.getElementById(ROOT_ID); if (tab && root && root.contains(tab)) { event.preventDefault(); event.stopPropagation(); setTab(tab.dataset.stgTab); return; } if (actionEl && root && root.contains(actionEl)) { event.preventDefault(); event.stopPropagation(); if (actionEl.dataset.stgAction === 'toggle' && Date.now() < skipClickUntil) return; action(actionEl.dataset.stgAction, actionEl); return; } if (theater) { event.preventDefault(); event.stopPropagation(); theaterAction(theater.dataset.stgTheaterAction, theater); } }
  function onChange(event) { const el = event.target; if (!el) return; if (el.dataset.stgImport) return importPrompts(el); if (el.matches('[data-stg-setting],[data-stg-profile],[data-stg-prompt]')) updateField(el); }
  function onInput(event) { const el = event.target; if (el && el.matches && el.matches('[data-stg-setting],[data-stg-profile],[data-stg-prompt]') && el.type !== 'checkbox' && el.tagName !== 'SELECT') updateField(el); }
  function togglePanel(force) { const panel = document.querySelector('#' + ROOT_ID + ' [data-stg-panel]'); if (!panel) return; panel.classList.toggle('stg-open', typeof force === 'boolean' ? force : !panel.classList.contains('stg-open')); if (panel.classList.contains('stg-open')) renderAll(); }
  function setTab(name) { document.querySelectorAll('#' + ROOT_ID + ' [data-stg-tab]').forEach(function (el) { el.classList.toggle('stg-active', el.dataset.stgTab === name); }); document.querySelectorAll('#' + ROOT_ID + ' [data-stg-section]').forEach(function (el) { el.classList.toggle('stg-active', el.dataset.stgSection === name); }); render(name); }

  function row(label, content) { return '<div class="stg-row"><label class="stg-label">' + escapeHtml(label) + '</label>' + content + '</div>'; }
  function switchHtml(key, label, hint, checked, chatSetting) { return '<div class="stg-row-inline"><div><div class="stg-label">' + escapeHtml(label) + '</div><div class="stg-subtle">' + escapeHtml(hint) + '</div></div><label class="stg-switch"><input type="checkbox" data-stg-setting="' + escapeHtml(key) + '"' + (chatSetting ? ' data-stg-chat="1"' : '') + (checked ? ' checked' : '') + '><span class="stg-slider"></span></label></div>'; }
  function selectHtml(key, value, options, prefix) { return '<select class="stg-select" ' + (prefix || 'data-stg-setting') + '="' + escapeHtml(key) + '">' + options.map(function (o) { return '<option value="' + escapeHtml(o[0]) + '"' + (String(o[0]) === String(value) ? ' selected' : '') + '>' + escapeHtml(o[1]) + '</option>'; }).join('') + '</select>'; }
  function renderAll() { ['general', 'api', 'prompts', 'history', 'manual'].forEach(render); }
  function render(name) { const el = document.querySelector('#' + ROOT_ID + ' [data-stg-section="' + name + '"]'); if (!el) return; if (name === 'general') el.innerHTML = generalHtml(); if (name === 'api') el.innerHTML = apiHtml(); if (name === 'prompts') el.innerHTML = promptsHtml(); if (name === 'history') el.innerHTML = historyHtml(); if (name === 'manual') el.innerHTML = '<div class="stg-grid"><div class="stg-subtle">对当前聊天最后一条正常 AI 回复手动生成。</div><button class="stg-action stg-primary" data-stg-action="manual">生成最后一条</button><button class="stg-action" data-stg-action="restore">恢复窗口</button></div>'; }
  function generalHtml() { const data = chatData(); return '<div class="stg-grid">' + switchHtml('enabled', '插件总开关', '关闭后自动和手动生成都停止。', !!settings.enabled) + switchHtml('autoGenerate', 'AI 回复完成后自动生成', '默认关闭，只处理完整正常的 AI 回复。', !!settings.autoGenerate) + switchHtml('chatEnabled', '当前聊天启用', '每个聊天可单独关闭。', !!data.enabled, true) + switchHtml('sendCharacterCard', '发送角色卡设定', '发送当前角色卡能读取到的设定。', !!settings.sendCharacterCard) + switchHtml('sendWorldbook', '发送已启用世界书条目', '尽力读取当前壳暴露的启用条目。', !!settings.sendWorldbook) + switchHtml('sendPreviousUser', '发送用户上一条消息', '上下文为 0 时仍可发送。', !!settings.sendPreviousUser) + row('上下文深度', selectHtml('contextDepth', String(settings.contextDepth), [['0', '只发送当前 AI 回复'], ['5', '最近 5 条'], ['10', '最近 10 条'], ['20', '最近 20 条'], ['custom', '自定义条数']])) + row('自定义条数', '<input class="stg-input" type="number" min="0" max="100" data-stg-setting="customContext" value="' + Number(settings.contextDepth || 0) + '">') + row('多提示词处理', selectHtml('promptMode', settings.promptMode, [['merged', '合并后请求一次 API'], ['separate', '分别请求并分区显示']])) + switchHtml('allowScripts', '在沙盒中渲染 JS', '默认只保留 HTML；打开后使用 sandbox iframe。', !!settings.allowScripts) + '</div>'; }
  function currentProfile() { let profile = settings.profiles.find(function (x) { return x.id === settings.activeProfile; }); if (!profile) { profile = settings.profiles[0]; settings.activeProfile = profile.id; } return profile; }
  function apiHtml() { const p = currentProfile(); function input(key, label, type) { return row(label, '<input class="stg-input" data-stg-profile="' + escapeHtml(key) + '" type="' + (type || 'text') + '" value="' + escapeHtml(p[key] == null ? '' : p[key]) + '">'); } return '<div class="stg-grid">' + row('API 档案', selectHtml('activeProfile', settings.activeProfile, settings.profiles.map(function (x) { return [x.id, x.name || '未命名']; }))) + '<div class="stg-button-row"><button class="stg-action" data-stg-action="addProfile">新增档案</button><button class="stg-action" data-stg-action="deleteProfile">删除档案</button><button class="stg-action" data-stg-action="models">获取模型</button></div>' + input('name', '档案名称') + input('baseUrl', 'API 地址') + input('apiKey', 'API Key', 'password') + input('model', '模型名称') + input('temperature', '温度', 'number') + input('maxTokens', '最大输出长度', 'number') + switchHtml('stream', '流式输出', '按当前档案选择普通或流式请求。', !!p.stream) + '<button class="stg-action stg-primary" data-stg-action="test">测试 API</button></div>'; }
  function promptsHtml() { return '<div class="stg-grid"><div class="stg-button-row"><button class="stg-action stg-primary" data-stg-action="addPrompt">新增提示词</button><button class="stg-action" data-stg-action="exportPrompts">导出</button><label class="stg-action">导入<input class="stg-hidden" type="file" accept="application/json" data-stg-import="1"></label></div><div class="stg-list">' + (settings.prompts.length ? settings.prompts.map(promptCard).join('') : '<div class="stg-subtle">没有提示词。</div>') + '</div></div>'; }
  function promptCard(prompt, index) { return '<article class="stg-card" data-stg-prompt-id="' + escapeHtml(prompt.id) + '"><div class="stg-card-head"><strong>' + escapeHtml(prompt.name || '未命名') + '</strong><span class="stg-pill">' + escapeHtml(prompt.category || '未分类') + '</span></div>' + row('名称', '<input class="stg-input" data-stg-prompt="name" value="' + escapeHtml(prompt.name || '') + '">') + row('分类', '<input class="stg-input" data-stg-prompt="category" value="' + escapeHtml(prompt.category || '') + '">') + row('正文', '<textarea class="stg-textarea" data-stg-prompt="text">' + escapeHtml(prompt.text || '') + '</textarea>') + '<div class="stg-button-row"><button class="stg-icon-btn" data-stg-action="promptUp" title="上移">' + iconFor('up') + '</button><button class="stg-icon-btn" data-stg-action="promptDown" title="下移">' + iconFor('down') + '</button><button class="stg-icon-btn" data-stg-action="promptCopy" title="复制">' + iconFor('copy') + '</button><button class="stg-icon-btn" data-stg-action="promptDelete" title="删除">' + iconFor('trash') + '</button><label class="stg-subtle"><input type="checkbox" data-stg-prompt="enabled"' + (prompt.enabled ? ' checked' : '') + '> 启用</label></div></article>'; }
  function exportPrompts() { const blob = new Blob([JSON.stringify(settings.prompts, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'stage-theater-prompts.json'; document.body.appendChild(link); link.click(); link.remove(); setTimeout(function () { URL.revokeObjectURL(link.href); }, 0); }
  function importPrompts(input) { const file = input && input.files && input.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = function () { try { const value = JSON.parse(String(reader.result || '[]')); const list = Array.isArray(value) ? value : value.prompts; if (!Array.isArray(list)) throw new Error('格式不是提示词列表'); settings.prompts = list.map(function (item) { return { id: makeId(), name: String(item.name || '未命名'), category: String(item.category || '未分类'), note: String(item.note || ''), enabled: item.enabled !== false, text: String(item.text || item.prompt || '') }; }); saveSettings(); render('prompts'); setStatus('提示词导入完成。'); } catch (error) { setStatus('导入失败：' + error.message); } input.value = ''; }; reader.readAsText(file); }
  function historyHtml() { return '<div class="stg-subtle">当前聊天的生成结果保存在消息下方窗口。收藏结果在这里按消息索引记录。</div>'; }
  function updateField(el) { if (el.dataset.stgChat) { chatData().enabled = !!el.checked; saveChat(); return; } if (el.dataset.stgSetting) { const key = el.dataset.stgSetting; if (key === 'customContext') settings.contextDepth = Math.max(0, Number(el.value || 0)); else if (key === 'stream') currentProfile().stream = !!el.checked; else if (el.type === 'checkbox') settings[key] = !!el.checked; else if (key === 'contextDepth') settings.contextDepth = el.value === 'custom' ? settings.contextDepth : Number(el.value); else if (key === 'activeProfile') settings.activeProfile = el.value; else settings[key] = el.value; saveSettings(); renderAll(); return; } if (el.dataset.stgProfile) { const p = currentProfile(), key = el.dataset.stgProfile; p[key] = ['temperature', 'maxTokens'].includes(key) ? Number(el.value || 0) : el.value; saveSettings(); return; } if (el.dataset.stgPrompt) { const card = el.closest('[data-stg-prompt-id]'), prompt = settings.prompts.find(function (x) { return x.id === (card && card.dataset.stgPromptId); }); if (!prompt) return; prompt[el.dataset.stgPrompt] = el.type === 'checkbox' ? !!el.checked : el.value; saveSettings(); } }
  function action(name, el) { if (name === 'toggle') return togglePanel(); if (name === 'close') return togglePanel(false); if (name === 'addProfile') { settings.profiles.push({ id: makeId(), name: '新 API 档案', baseUrl: '', apiKey: '', model: '', temperature: 0.9, maxTokens: 800, stream: false }); settings.activeProfile = settings.profiles[settings.profiles.length - 1].id; saveSettings(); render('api'); } else if (name === 'deleteProfile') { if (settings.profiles.length <= 1) return setStatus('至少保留一个 API 档案。'); settings.profiles = settings.profiles.filter(function (x) { return x.id !== settings.activeProfile; }); settings.activeProfile = settings.profiles[0].id; saveSettings(); render('api'); } else if (name === 'models') fetchModels(); else if (name === 'test') testApi(); else if (name === 'addPrompt') { settings.prompts.push({ id: makeId(), name: '新小剧场', category: '通用', note: '', enabled: true, text: '' }); saveSettings(); render('prompts'); } else if (name === 'promptDelete') { const card = el.closest('[data-stg-prompt-id]'); settings.prompts = settings.prompts.filter(function (x) { return x.id !== card.dataset.stgPromptId; }); saveSettings(); render('prompts'); } else if (name === 'promptCopy') { const card = el.closest('[data-stg-prompt-id]'), source = settings.prompts.find(function (x) { return x.id === card.dataset.stgPromptId; }); if (source) settings.prompts.push(Object.assign({}, clone(source), { id: makeId(), name: source.name + ' 副本' })); saveSettings(); render('prompts'); } else if (name === 'promptUp' || name === 'promptDown') { const card = el.closest('[data-stg-prompt-id]'), index = settings.prompts.findIndex(function (x) { return x.id === card.dataset.stgPromptId; }), target = index + (name === 'promptUp' ? -1 : 1); if (index >= 0 && target >= 0 && target < settings.prompts.length) { const item = settings.prompts.splice(index, 1)[0]; settings.prompts.splice(target, 0, item); saveSettings(); render('prompts'); } } else if (name === 'manual') { const message = lastAssistant(); if (message) generate(message, 'manual'); else setStatus('没有找到正常的 AI 回复。'); } else if (name === 'restore') restoreWindows(); }
  function lastAssistant() { const list = messages(); for (let i = list.length - 1; i >= 0; i--) { if (!isAssistant(list[i])) continue; const text = bodyOf(list[i]).trim(); if (text) return { index: i, key: messageKey(i, list[i]), message: list[i], text: text }; } return null; }
  function buildRequest(message) { const prompts = settings.prompts.filter(function (x) { return x.enabled && String(x.text || '').trim(); }); const promptBlock = prompts.map(function (p, i) { return '【提示词 ' + (i + 1) + '：' + p.name + '】\n' + p.text; }).join('\n\n'); const parts = []; if (settings.sendCharacterCard) parts.push('【角色卡设定】\n' + characterCard()); if (settings.sendWorldbook) parts.push('【已启用世界书】\n' + worldbook()); const depth = Math.max(0, Number(settings.contextDepth || 0)); if (depth) parts.push('【最近聊天上下文】\n' + messages().slice(Math.max(0, message.index - depth + 1), message.index + 1).map(function (m) { return (isUser(m) ? '用户' : isSystem(m) ? '系统' : 'AI') + '：' + bodyOf(m).trim(); }).join('\n')); if (settings.sendPreviousUser) { for (let i = message.index - 1; i >= 0; i--) if (isUser(messages()[i])) { parts.push('【用户上一条消息】\n' + bodyOf(messages()[i]).trim()); break; } } parts.push('【触发的 AI 回复】\n' + message.text); parts.push('【小剧场提示词】\n' + promptBlock); return { system: '你是独立小剧场生成器。只输出小剧场正文，不要解释任务，不要复述输入。可以使用基础 HTML 排版。' + (settings.promptMode === 'merged' ? '多条提示词合并理解，一次生成一个完整回复，自行分区。' : '多条提示词分别生成并用 HTML 区块分隔。'), user: parts.join('\n\n') }; }
  function characterCard() { const c = context(), card = [c.character, c.characters && c.characters[c.characterId], c.characters && c.characters[c.this_chid], window.characters && window.characters[window.this_chid], c.char].find(function (x) { return x && typeof x === 'object'; }) || {}; return [['角色名', card.name || c.name2 || window.name2], ['描述', card.description || card.desc], ['性格', card.personality], ['场景', card.scenario], ['首条消息', card.first_mes || card.firstMessage], ['示例对话', card.mes_example || card.example_dialogue]].filter(function (x) { return x[1]; }).map(function (x) { return x[0] + '：' + String(x[1]).trim(); }).join('\n\n').slice(0, 16000); }
  function worldbook() { const c = context(), pool = [c.world_info, c.worldInfo, c.worldbook, c.worlds, window.world_info, window.worldInfo].filter(Boolean), result = []; function walk(value) { if (!value || result.length > 100) return; if (Array.isArray(value)) return value.forEach(walk); if (typeof value !== 'object') return; const content = value.content || value.entry || value.text, disabled = value.disabled === true || value.disable === true || value.enabled === false; if (content && !disabled) result.push(String(content).trim()); else Object.values(value).forEach(walk); } pool.forEach(walk); return result.join('\n\n').slice(0, 20000); }
  function endpoints(base, suffix) { const clean = String(base || '').replace(/\/+$/, ''); if (!clean) return []; return /\/v1$/i.test(clean) ? [clean + suffix, clean.replace(/\/v1$/i, '') + suffix] : [clean + suffix, clean + '/v1' + suffix]; }
  async function fetchModels() { const profile = currentProfile(); if (!profile.baseUrl || !profile.apiKey) return setStatus('请先填写 API 地址和 API Key。'); setStatus('正在获取模型列表...'); for (const url of endpoints(profile.baseUrl, '/models')) { try { const response = await fetch(url, { headers: { Authorization: 'Bearer ' + profile.apiKey } }); if (!response.ok) continue; const data = await response.json(); const list = Array.isArray(data && data.data) ? data.data.map(function (item) { return item && item.id; }).filter(Boolean) : []; if (list.length) { profile.model = String(list[0]); saveSettings(); render('api'); return setStatus('已获取 ' + list.length + ' 个模型，已填入第一个。'); } } catch (_) {} } setStatus('获取模型失败，请检查地址、密钥和跨域设置。'); }
  async function testApi() { const profile = currentProfile(); if (!profile.baseUrl || !profile.apiKey || !profile.model) return setStatus('请先填写 API 地址、API Key 和模型名称。'); setStatus('正在测试 API...'); try { const result = await request(profile, { system: '只回复 OK。', user: '连接测试。' }); setStatus(result ? 'API 连接成功。' : 'API 返回为空。'); } catch (error) { setStatus('API 测试失败：' + error.message); } }
  async function request(profile, requestData) {
    const payload = { model: profile.model, temperature: Number(profile.temperature || 0.9), max_tokens: Number(profile.maxTokens || 800), messages: [{ role: 'system', content: requestData.system }, { role: 'user', content: requestData.user }] };
    for (const url of endpoints(profile.baseUrl, '/chat/completions')) {
      const controller = new AbortController(), timer = setTimeout(function () { controller.abort(); }, 60000);
      try {
        const response = await fetch(url, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: 'Bearer ' + profile.apiKey }, body: JSON.stringify(Object.assign({}, payload, { stream: !!profile.stream })), signal: controller.signal });
        if (!response.ok) continue;
        if (!profile.stream || !response.body || !response.body.getReader) {
          const data = await response.json();
          return data && data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content || '';
        }
        const reader = response.body.getReader(), decoder = new TextDecoder(), chunks = [];
        let buffer = '';
        while (true) {
          const part = await reader.read();
          if (part.done) break;
          buffer += decoder.decode(part.value, { stream: true });
          const lines = buffer.split(/\r?\n/);
          buffer = lines.pop() || '';
          lines.forEach(function (line) { const value = line.replace(/^data:\s*/, '').trim(); if (!value || value === '[DONE]') return; try { const item = JSON.parse(value), delta = item.choices && item.choices[0] && item.choices[0].delta; if (delta && delta.content) chunks.push(delta.content); } catch (_) {} });
        }
        return chunks.join('');
      } catch (_) {
        if (profile.stream) profile.stream = false;
      } finally { clearTimeout(timer); }
    }
    return '';
  }
  function messageElement(message) { const all = Array.from(document.querySelectorAll('#chat .mes, #chat [mesid], .mes')); return document.querySelector('#chat [mesid="' + message.index + '"]') || document.querySelector('[mesid="' + message.index + '"]') || all[message.index] || null; }
  function sanitizeHtml(value) { const box = document.createElement('div'); box.innerHTML = String(value || ''); box.querySelectorAll('script, iframe, object, embed, link, meta').forEach(function (node) { node.remove(); }); box.querySelectorAll('*').forEach(function (node) { Array.from(node.attributes).forEach(function (attribute) { if (/^on/i.test(attribute.name) || /^(javascript|vbscript):/i.test(attribute.value)) node.removeAttribute(attribute.name); }); }); return box.innerHTML; }
  function renderContent(body, content) { body.innerHTML = ''; if (settings.allowScripts && /<script\b/i.test(String(content || ''))) { const frame = document.createElement('iframe'); frame.setAttribute('sandbox', 'allow-scripts'); frame.setAttribute('referrerpolicy', 'no-referrer'); frame.srcdoc = String(content || ''); body.appendChild(frame); } else body.innerHTML = sanitizeHtml(content); }
  function renderWindow(message, data, preview) { const anchor = messageElement(message); if (!anchor) return; let host = anchor.querySelector('.stg-theater-host'); if (!host) { host = document.createElement('div'); host.className = 'stg-theater-host'; anchor.appendChild(host); } const current = data && data.current || { title: '小剧场', content: preview || '' }; const favorites = data && Array.isArray(data.favorites) ? data.favorites : []; const favoriteHtml = favorites.length ? '<div class="stg-fav-strip">' + favorites.map(function (item, index) { return '<button type="button" class="stg-fav-chip" data-stg-theater-action="showFavorite" data-stg-favorite-index="' + index + '" title="显示收藏">' + escapeHtml(item.title || ('收藏 ' + (index + 1))) + '</button>'; }).join('') + '</div>' : ''; host.innerHTML = '<section class="stg-theater-window" data-stg-message-key="' + escapeHtml(message.key) + '"><header class="stg-theater-head"><strong class="stg-theater-title">' + icon + '<span>' + escapeHtml(current.title) + '</span></strong><div class="stg-theater-tools"><button type="button" class="stg-icon-btn" data-stg-theater-action="collapse" title="折叠">' + iconFor('collapse') + '</button><button type="button" class="stg-icon-btn" data-stg-theater-action="regenerate" title="重新生成">' + iconFor('refresh') + '</button><button type="button" class="stg-icon-btn" data-stg-theater-action="favorite" title="收藏">' + iconFor('star') + '</button><button type="button" class="stg-icon-btn" data-stg-theater-action="copy" title="复制">' + iconFor('copy') + '</button><button type="button" class="stg-icon-btn" data-stg-theater-action="edit" title="编辑">' + iconFor('edit') + '</button><button type="button" class="stg-icon-btn" data-stg-theater-action="delete" title="删除此条">' + iconFor('trash') + '</button></div></header>' + favoriteHtml + '<div class="stg-theater-body"></div></section>'; renderContent(host.querySelector('.stg-theater-body'), current.content); }
  function restoreWindows() { const data = chatData(); messages().forEach(function (message, index) { if (!isAssistant(message)) return; const key = messageKey(index, message); if (data.theaters[key] && data.theaters[key].current) renderWindow({ index: index, key: key, text: bodyOf(message).trim() }, data.theaters[key]); }); }
  function theaterAction(name, el) { const win = el.closest('.stg-theater-window'), key = win && win.dataset.stgMessageKey, data = key && chatData().theaters[key]; if (!data) return; if (name === 'collapse') win.classList.toggle('stg-collapsed'); else if (name === 'regenerate') { const list = messages(); for (let i = 0; i < list.length; i++) if (messageKey(i, list[i]) === key) return generate({ index: i, key: key, text: bodyOf(list[i]).trim() }, 'regenerate'); } else if (name === 'favorite') { data.favorites = data.favorites || []; data.favorites.push(clone(data.current)); saveChat(); renderWindow({ index: messages().findIndex(function (item, index) { return messageKey(index, item) === key; }), key: key }, data); setStatus('已收藏。'); } else if (name === 'showFavorite') { const index = Number(el.dataset.stgFavoriteIndex); if (data.favorites[index]) { const previous = data.current; data.current = data.favorites[index]; renderWindow({ index: messages().findIndex(function (item, itemIndex) { return messageKey(itemIndex, item) === key; }), key: key }, data); data.current = previous; } } else if (name === 'delete') { delete chatData().theaters[key]; saveChat(); win.closest('.stg-theater-host').remove(); } else if (name === 'edit') { const body = win.querySelector('.stg-theater-body'); body.innerHTML = '<textarea class="stg-edit-box">' + escapeHtml(data.current.content) + '</textarea><button class="stg-action stg-primary" data-stg-save-edit>保存编辑</button>'; body.querySelector('[data-stg-save-edit]').addEventListener('click', function () { data.current.content = body.querySelector('textarea').value; saveChat(); restoreWindows(); }); } else if (name === 'copy' && navigator.clipboard) navigator.clipboard.writeText(data.current.content).then(function () { setStatus('已复制。'); }); }
  async function generate(message, source) { if (generating) return; const profile = currentProfile(), prompts = settings.prompts.filter(function (x) { return x.enabled && String(x.text || '').trim(); }); if (!profile.baseUrl || !profile.apiKey || !profile.model || !prompts.length) return setStatus('请先配置 API 和启用提示词。'); generating = true; const data = chatData(), old = clone(data.theaters[message.key] || { favorites: [] }); renderWindow(message, data.theaters[message.key], '正在生成小剧场...'); try { const result = await request(profile, buildRequest(message)); if (!result) throw new Error('API 返回为空'); data.theaters[message.key] = { current: { title: prompts.length === 1 ? prompts[0].name : '合并小剧场', content: result, source: source, createdAt: Date.now(), sourceHash: hash(message.text) }, favorites: old.favorites || [] }; saveChat(); renderWindow(message, data.theaters[message.key]); setStatus('小剧场生成完成。'); } catch (error) { data.theaters[message.key] = old; renderWindow(message, old); setStatus('生成失败：' + (error.message || '请求异常')); } finally { generating = false; } }
  function complete(message) { return !!message && !message.is_incomplete && !message.interrupted && !message.error && !/^(error|exception|failed|network error|api error)\b/i.test(bodyOf(message).trim()); }
  async function maybeAuto() { if (generating || !settings.enabled || !settings.autoGenerate || !chatData().enabled) return; const message = lastAssistant(); if (!message || !complete(message)) return; const signature = message.key + ':' + hash(message.text); if (signature === generatedSignature) return; if (signature !== pendingSignature) { pendingSignature = signature; pendingSince = Date.now(); return; } if (Date.now() - pendingSince < 700) return; generatedSignature = signature; await generate(message, 'auto'); }
  function subscribe() { if (subscribed) return; subscribed = true; const c = context(), source = c.eventSource || window.eventSource, types = c.event_types || window.event_types || {}, name = types.MESSAGE_RECEIVED || types.GENERATION_ENDED || types.MESSAGE_UPDATED || types.MESSAGE_SENT; if (source && typeof source.on === 'function' && name) { try { source.on(name, function () { setTimeout(maybeAuto, 800); }); } catch (_) {} } setInterval(maybeAuto, 1800); }
  function setStatus(value) { const el = document.querySelector('#' + ROOT_ID + ' [data-stg-status]'); if (el) el.textContent = value || ''; console.log('[stage-theater]', value || ''); }
  function init() { if (initialized || !document.body) return; if (!mount()) return; bindEvents(); initialized = true; restoreWindows(); subscribe(); setStatus('已加载。'); }
  let fired = false;
  function fire() { if (fired || !document.body) return; try { init(); if (initialized) fired = true; } catch (error) { console.warn('[stage-theater] 初始化失败', error); } }
  try { const c = context(), source = c.eventSource || window.eventSource, types = c.event_types || window.event_types || {}; if (source && typeof source.on === 'function' && types.APP_READY) source.on(types.APP_READY, fire); } catch (_) {}
  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', fire, { once: true }); else fire();
  window.addEventListener('load', fire, { once: true });
  const started = Date.now(), timer = setInterval(function () { if (document.body) fire(); if (fired || Date.now() - started > 5000) clearInterval(timer); }, 250);
})();
